Sitegeist:
  FusionForm:
    FriendlyCaptcha:
      siteKey: ''
      siteSecret: ''
Neos:
  Fusion:
    defaultContext:
      FriendlyCaptcha: 'Sitegeist\FusionForm\FriendlyCaptcha\Eel\FriendlyCaptchaHelper'
  Neos:
    fusion:
      autoInclude:
        Sitegeist.FusionForm.FriendlyCaptcha: true
